name: bank_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.2.0
  flutter_credit_card: ^3.0.6
  get: ^4.6.5
  flutter_launcher_icons: "^0.9.2"
  flutter_flip_card: ^0.0.4
  intl: ^0.18.1
  faker: ^2.1.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11
  mailer: ^6.0.1
  qr_flutter: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/icons/
